/*
 * File: .github/workflows/ci.yml
 * Description: GitHub Actions workflow configuration.
 */
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain

      - name: Run Tests
        run: ./gradlew test
